name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull official postgres and pgadmin images
        run: |
          docker pull postgres:latest
          docker pull dpage/pgadmin4:latest

      - name: Set up docker-compose services
        run: |
          docker-compose up -d

      - name: Wait for services to be ready
        run: |
          sleep 15
          docker ps

      # Aquí puedes agregar comandos para testear la conexión a la DB o pgAdmin

      - name: Shut down services
        run: docker-compose down
