name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull official postgres and pgadmin images
        run: |
          docker pull postgres:latest
          docker pull dpage/pgadmin4:latest

      - name: Create custom postgres image (optional)
        run: |
          docker build -t my-postgres ./path/to/postgres/

      - name: Create custom pgadmin image (optional)
        run: |
          docker build -t my-pgadmin ./path/to/pgadmin/
